/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Color: typeof import('./src/components/color.vue')['default']
    Contact: typeof import('./src/components/contact.vue')['default']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    Operate: typeof import('./src/components/operate.vue')['default']
    Scale: typeof import('./src/components/scale.vue')['default']
  }
}
